Repository kataya1/Pinterest, pull requests merged in 2021-11, with the labels that each got.

#1 mkdir .github
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Quality_of_Life.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: good first issue, setup 🔧

#13 Models by moaaz
  backend/backend/accounts/admin.py
  backend/backend/accounts/migrations/0001_initial.py
  backend/backend/accounts/migrations/0002_initial.py
  backend/backend/accounts/models.py
  backend/backend/accounts/views.py
  backend/backend/pins/__init__.py
  backend/backend/pins/admin.py
  backend/backend/pins/apps.py
  backend/backend/pins/migrations/0001_initial.py
  backend/backend/pins/migrations/0002_alter_reply_time.py
  backend/backend/pins/migrations/__init__.py
  backend/backend/pins/models.py
  backend/backend/pins/tests.py
  backend/backend/pins/views.py
Labels: enhancement

#17 good old copy past 😅
  backend/backend/accounts/admin.py
  backend/backend/accounts/migrations/0001_initial.py
  backend/backend/accounts/migrations/0002_user_interest.py
  backend/backend/accounts/models.py
  backend/backend/accounts/views.py
  backend/backend/backend/settings.py
  backend/backend/pins/__init__.py
  backend/backend/pins/admin.py
  backend/backend/pins/apps.py
  backend/backend/pins/migrations/0001_initial.py
  backend/backend/pins/migrations/__init__.py
  backend/backend/pins/models.py
  backend/backend/pins/tests.py
  backend/backend/pins/views.py
Labels: enhancement, setup 🔧

#23 User API
  backend/backend/accounts/api/v1/serializers.py
  backend/backend/accounts/api/v1/urls.py
  backend/backend/accounts/api/v1/view.py
  backend/backend/accounts/api/v1/views.py
  backend/backend/accounts/apps.py
  backend/backend/accounts/migrations/0003_auto_20211120_2303.py
  backend/backend/accounts/migrations/0004_alter_user_following.py
  backend/backend/accounts/migrations/0005_user_saved_pins.py
  backend/backend/accounts/models.py
  backend/backend/accounts/signals.py
  backend/backend/accounts/views.py
  backend/backend/backend/settings.py
  backend/backend/backend/urls.py
  backend/backend/pins/migrations/0002_remove_pin_saved_by.py
  backend/backend/pins/models.py
Labels: enhancement

#29 fixed navbar and svg colors
  frontend/pintrest/src/components/Home/Anq-btns.css
  frontend/pintrest/src/components/Navbar/Navbar.css
  frontend/pintrest/src/components/Navbar/Navbar.js
  frontend/pintrest/src/components/Navbar/Navbar.module.css
  frontend/pintrest/src/components/Navbar/Searchbox/Searchbox.css
  frontend/pintrest/src/components/Navbar/Searchbox/Searchbox.js
  frontend/pintrest/src/components/Navbar/Searchbox/Searchbox.module.css
  frontend/pintrest/src/components/Navbar/Searchbox/magni.svg
  frontend/pintrest/src/components/Searchbox/Searchbox.js
Labels: bug
